### PR TITLE
Feature/431 update roadmap pdf texts

### PR DESCRIPTION
**Pull request by navins94**
Below things are changed in roadmap pdf

Living income superscript
Footer text superscript
Background text

### CODE REVIEW

**Review by wayangalihpratama — APPROVED** [review]

**Review by wayangalihpratama — CHANGES_REQUESTED** [review]
I didn't see any updates on `roadmap.json` file? 
I think we need too incorporate "Living Income" section ?

**Review by wayangalihpratama — COMMENTED** [review]
Hi @navins94 , 
Why are all the IDs updated? 
I thought we copied the old roadmap to example-initial-value on akvo-react-form-editor, then add new living income group.

**Comment by navins94** [comment]
> Hi @navins94 , Why are all the IDs updated? I thought we copied the old roadmap to example-initial-value on akvo-react-form-editor, then add new living income group.

I wasn't aware that we can copy initial values. I can update it

**Comment by wayangalihpratama** [comment]
> > Hi @navins94 , Why are all the IDs updated? I thought we copied the old roadmap to example-initial-value on akvo-react-form-editor, then add new living income group.
> 
> I wasn't aware that we can copy initial values. I can update it. @wayangalihpratama where can I copy I don't see any option Screenshot 2023-04-13 at 6 31 42 AM

Hi Navin, 
I was told the step on Slack chat to run akvo-react-form-editor locally, so we can replace the example initial value.

**Comment by navins94** [comment]
> > > Hi @navins94 , Why are all the IDs updated? I thought we copied the old roadmap to example-initial-value on akvo-react-form-editor, then add new living income group.
> > 
> > 
> > I wasn't aware that we can copy initial values. I can update it. @wayangalihpratama where can I copy I don't see any option Screenshot 2023-04-13 at 6 31 42 AM
> 
> Hi Navin, I was told the step on Slack chat to run akvo-react-form-editor locally, so we can replace the example initial value.

Yes, Sorry I missed that part. I have reverted the old Ids

**Comment by wayangalihpratama** [comment]
Hi @navins94 , 
Can you please rebase/merge develop branch into this branch.

**Review by wayangalihpratama — CHANGES_REQUESTED** [review]
Hi @navins94 , 
selenium test failed when i run 
`docker-compose exec selenium ./run.sh`

```bash
error: invalid session id
info: Finished test open_manage_user_page Failure
warn: Completed with failure
 FAIL  ../usr/local/lib/node_modules/selenium-side-runner/dist/main.test.js (36.254 s)
  Running project ISCO
    Running suite login_with_verified_super_admin
      ✓ Running test login_with_verified_super_admin (5864 ms)
    Running suite isco_authentication
      ✓ Running test 00_clean_up_test_user (2746 ms)
      ✓ Running test 01_register_new_user (6836 ms)
    Running suite isco_admin_page
      ✕ Running test open_manage_user_page (20334 ms)

  ● Running project ISCO › Running suite isco_admin_page › Running test open_manage_user_page

    Operation timed out running command open:/admin:

      at Timeout.<anonymous> (node_modules/@seleniumhq/side-runtime/src/playback-tree/command-node.ts:151:13)

  ● Running project ISCO › Running suite isco_admin_page › Running test open_manage_user_page

    thrown: true

      at node_modules/jest-each/build/bind.js:43:11
          at Array.forEach (<anonymous>)
      at src/main.test.ts:150:9
          at Array.forEach (<anonymous>)

Test Suites: 1 failed, 1 total
Tests:       1 failed, 3 passed, 4 total
Snapshots:   0 total
Time:        36.297 s
```

**Comment by navins94** [comment]
> Hi @navins94 , selenium test failed when I run `docker-compose exec selenium ./run.sh`
> 
> ```shell
> error: invalid session id
> info: Finished test open_manage_user_page Failure
> warn: Completed with failure
>  FAIL  ../usr/local/lib/node_modules/selenium-side-runner/dist/main.test.js (36.254 s)
>   Running project ISCO
>     Running suite login_with_verified_super_admin
>       ✓ Running test login_with_verified_super_admin (5864 ms)
>     Running suite isco_authentication
>       ✓ Running test 00_clean_up_test_user (2746 ms)
>       ✓ Running test 01_register_new_user (6836 ms)
>     Running suite isco_admin_page
>       ✕ Running test open_manage_user_page (20334 ms)
> 
>   ● Running project ISCO › Running suite isco_admin_page › Running test open_manage_user_page
> 
>     Operation timed out running command open:/admin:
> 
>       at Timeout.<anonymous> (node_modules/@seleniumhq/side-runtime/src/playback-tree/command-node.ts:151:13)
> 
>   ● Running project ISCO › Running suite isco_admin_page › Running test open_manage_user_page
> 
>     thrown: true
> 
>       at node_modules/jest-each/build/bind.js:43:11
>           at Array.forEach (<anonymous>)
>       at src/main.test.ts:150:9
>           at Array.forEach (<anonymous>)
> 
> Test Suites: 1 failed, 1 total
> Tests:       1 failed, 3 passed, 4 total
> Snapshots:   0 total
> Time:        36.297 s
> ```

Hi @wayangalihpratama ,

I am not getting that error when I run that command. Maybe your backend was not started or something like that

**Pull request merged**
